### PR TITLE
Added the production server and static handling

### PR DESCRIPTION
**Pull request by mohammadraufzahed**
Hi Mr. Sadegh, I added the Gunicorn production-ready server for handling requests that comes to the Django and API that have better performance and stability than the development server.
I also added a Caddy server for reverse proxy and static file handling.

In the next step, I will try to make the Postgres database secure by hiding its port in the next step and handling the Pgadmin requests with Caddy.

### CODE REVIEW

**Comment by mohammadraufzahed** [comment]
Also, I want to mention to the docker build tag that it will not reinstall all dependencies when a code changes, and this happens because we copy our requirements file before the source code, and the cache will not expire when a change applies to the source.

**Comment by sadeghesfahani** [comment]
hello Mr.Raufzzahed, thanks for your contribution, as I haven't had any experience with caddy, how can I test it? as you know this Backend server is used by 15 frontend developers in their final project so I need to test it before merging, another thing is that will be great if you can keep your migrations files out of the repo. thanks in advance.

**Comment by sadeghesfahani** [comment]
I added some hot fixes, please confirm them before merging

**Comment by mohammadraufzahed** [comment]
I will confirm the first and last commit, but the others commits are wrong.
The port 8000 is for the development server, and it doesn't use in production. We will handle the production requests with Gunicorn and the Caddy web server and expose them as 80 port and 443 port for SSL.
The Gunicorn WSGI will process our requests with better performance, also, we will manage its requests and assets with the Caddy webserver.
Also, as you mentioned, this project is used in production and can't use the Django development server.
> Note: Caddy Handles SSL automatically and all you must do is replace your production server URL with localhost in the Caddyfile

**Review by mohammadraufzahed — COMMENTED** [review]
It's not needed, you can access the backend with 80 and 443(SSL) ports.

**Review by mohammadraufzahed — COMMENTED** [review]
It's not needed, the Gunicorn will handle the requests without any problems.

**Comment by sadeghesfahani** [comment]
we need to have development environment due to probable issues might happen in the future, we need to ask our clients to send us the errors, with production environment it is not possible. so, we need port 8000 on that case too. if it is confirmed. we will merge it today.

**Comment by sadeghesfahani** [comment]
we need to have development environment due to probable issues might happen in the future, we need to ask our clients to send us the errors, with production environment it is not possible. so, we need port 8000 on that case too. if it is confirmed. we will merge it today.

**Comment by mohammadraufzahed** [comment]
If you need the errors log you must use a logger instead of the development server. This is not a good reason to use the development server in the production stage.
[Logging | Django](https://docs.djangoproject.com/en/4.0/topics/logging/)

**Comment by sadeghesfahani** [comment]
you are right by all means, but the project is being used by front-end developers at the same time for the final project, as I should maintain their needs for another 2 weeks, I prefer to compromise some security issues for simplicity during this phase. I appreciate it if you can work on it and wait two weeks for merging into the main. let this pull request stay open and work on other security issues for the time being. thanks for your contribution.

**Comment by mohammadraufzahed** [comment]
Of course, When you are ready to work on the production version, just send a new comment here to notify me.

**Comment by mohammadraufzahed** [comment]
Hi, any progress?

**Comment by sadeghesfahani** [comment]
it's just about to be finished, final review will be next Friday and we are ready to merge. by the way I will ask all if they don't wanna give the last updates, we can do the merge sooner

**Pull request merged**
